// https://leetcode.com/problems/partition-array-into-two-arrays-to-minimize-sum-difference/description/

class Solution {
private:
    vector<vector<long long>> get_sums(vector<int> &v)
    {
        vector<vector<long long>> sums;
        int n = v.size();
        sums.resize(n + 1);
        int totalsubset = 1 << n;
        for(int mask = 0; mask < totalsubset; mask++)
        {
            long long sum = 0;
            long long bit = __builtin_popcount(mask);
            if(bit > n) continue;
            for(int i = 0; i < n; i++)
            if(mask & (1 << i))
            sum += v[i];
            sums[bit].emplace_back(sum);
        }
        return sums;
    }
public:
    int minimumDifference(vector<int>& nums) {
        int n = nums.size();
        int n2 = n / 2;
        int mid = (n + 1) / 2;
        long long sum = accumulate(nums.begin(), nums.end(), 0ll);
        long long goal = sum/2;
        vector<int> v1, v2;
        for(int i = 0; i < mid; i++)
        v1.emplace_back(nums[i]);
        for(int i = mid; i < n; i++)
        v2.emplace_back(nums[i]);
        vector<vector<long long>> sums1 = get_sums(v1);
        vector<vector<long long>> sums2 = get_sums(v2);
        for(int i = 0; i < n2; i++)
        sort(sums2[i].begin(), sums2[i].end());
        long long sums1sz = sums1.size();
        long long mindiff = LLONG_MAX;
        for(int i = 0; i < sums1sz; i++)
        {
            for(auto s1 : sums1[i])
            {
                auto it = lower_bound(sums2[n2 - i].begin(), sums2[n2 - i].end(), goal - s1);
                if(it < sums2[n2 - i].end()) 
                mindiff = min(mindiff, abs(2 * (s1 + *it) - sum));
            }

            // This part isn't needed since this is the other combination which has been generated by other case.. 
            // eg. 001 and 110 in get_sums

            // if(it > sums2[n2 - i].begin())
            // {
            //     it--;
            //     mindiff = min(mindiff, abs(2 * (s1 + *it) - sum));
            // }
        }
        return mindiff;
    }
};